{application,protobuf_generate,
             [{modules,['Elixir.Mix.Tasks.Protobuf.Generate',
                        'Elixir.ProtobufGenerate.CodeGen',
                        'Elixir.ProtobufGenerate.Plugin',
                        'Elixir.ProtobufGenerate.Plugins.Enum',
                        'Elixir.ProtobufGenerate.Plugins.Extension',
                        'Elixir.ProtobufGenerate.Plugins.GRPC',
                        'Elixir.ProtobufGenerate.Plugins.GRPCWithOptions',
                        'Elixir.ProtobufGenerate.Plugins.Message',
                        'Elixir.ProtobufGenerate.Protoc']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,protobuf]},
              {description,"Protobuf code generation as a mix task"},
              {registered,[]},
              {vsn,"0.1.3"}]}.
