{application,grpc_core,
             [{modules,['Elixir.GRPC.Codec','Elixir.GRPC.Codec.Erlpack',
                        'Elixir.GRPC.Codec.JSON','Elixir.GRPC.Codec.Proto',
                        'Elixir.GRPC.Codec.WebText','Elixir.GRPC.Compressor',
                        'Elixir.GRPC.Compressor.Gzip','Elixir.GRPC.Core',
                        'Elixir.GRPC.Credential','Elixir.GRPC.Google.RPC',
                        'Elixir.GRPC.Message','Elixir.GRPC.RPCError',
                        'Elixir.GRPC.Service','Elixir.GRPC.Status',
                        'Elixir.GRPC.Telemetry','Elixir.GRPC.TimeUtils',
                        'Elixir.GRPC.Transport.HTTP2',
                        'Elixir.GRPC.Transport.Utils']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,protobuf,jason,
                             telemetry,googleapis]},
              {description,"Core gRPC types, codecs, and utilities for Elixir"},
              {registered,[]},
              {vsn,"1.0.0-rc.1"}]}.
