name: Cron CI

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  interop-tests:
    runs-on: ubuntu-latest
    name: Interop tests
    container:
      image: elixir:1.9.1-slim
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
      working-directory: ./interop
    - name: Run Cron CI
      run: ci-cron
