name: Cron CI

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  interop-tests:
    runs-on: ubuntu-latest
    name: Interop tests
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '23.2.4'
        elixir-version: '1.11.3'
    - name: Install dependencies
      run: mix deps.get
      working-directory: ./interop
    - name: Run Cron CI
      run: make ci-cron
