name: Elixir Dev Publish

env:
  SHA: ${{ github.sha }}
  JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DEBIAN_FRONTEND: noninteractive
  REPOSITORY: kafkaesque
  ELIXIR_VERSION: 1.10.x # Elixir version used during package publishing
  OTP_VERSION: 22.x # OTP version used during package publishing
  RUNNER_OS: ubuntu22 # Must match Elixir/OTP version in described in action erlef/setup-beam@v1
  RELEVANT_FILES: "mix.lock mix.exs lib config test"  # Important, this controls the caching, make sure to keep this right
  DEPENDENCY_FILE: mix.lock
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs: {}

jobs:
  dev-publish:
    name: Dev Publish
    runs-on: runs-on,runner=4cpu-linux-x64
    steps:
      - name: Publish Hex package
        uses: surgeventures/platform-tribe-actions/elixir/dev-publish@fast-elixir-repo-setup
        with:
          repository: ${{ env.REPOSITORY}}
          dependency-file: ${{ env.DEPENDENCY_FILE }}
          sha: ${{ env.SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          hex-token: ${{ secrets.HEX_ORGANIZATION_WRITE_KEY }}
          mix-env: dev
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
          runner-os: ${{ env.RUNNER_OS }}
          relevant-files: ${{ env.RELEVANT_FILES}}